trigger:
- main


stages:
  - stage: python
    displayName: python setup
    jobs:
      - job: python
        displayName: download and create env for python
        pool:
         vmImage: 'windows-latest'
        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azuresubscription: "justpracticerepo"
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: |
                git clone -b main https://github.hpe.com/hpe/HPE_FC_RPA_SUPPORT_BOTS.git temp_project
                mkdir -p /d/Projects/demo 
                cp /temp_project/HPE_FC_RPA_SUPPORT_BOTS/* /d/Projects/demo
