trigger:
- main


stages:
  - stage: python
    displayName: python setup
    jobs:
      - job: python
        displayName: download and create env for python
        pool:
         vmImage: 'windows-latest'
        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azuresubscription: "justpracticerepo"
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: |
                git clone -b dev https://github.com/Thiru799/taxi-booking.git temp_project
                ls
                mkdir -p /d/Projects/demo 
                cp -r temp_project/* /d/Projects/demo
                ls /d/Projects/demo/
          
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'justpracticerepo'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                python3 -m venv dev
                source dev/bin/activate
                export HTTPS_PROXY=http://proxy.its.hpecorp.net:8080
                pip install -r requirements.txt
                if [ $? -eq 0 ]; then
                    echo "Project setup completed successfully."
                else
                    echo "Project setup failed."
                    exit 1
                fi
